name: Helm deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Login to Quay
        run: docker login quay.io -u ${{ secrets.QUAY_USERNAME }} -p "${{ secrets.QUAY_PASSWORD }}"

      - name: Pull latest image to use for cache
        run: docker pull quay.io/lewagon/rails-k8s-demo:latest || true

      - name: Copy master key from a secret
        run: echo ${{ secrets.RAILS_MASTER_KEY }} > config/master.key

      - name: Build and push prod image
        run: make build-ci

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig show kubernetes-demo > $GITHUB_WORKSPACE/.kubeconfig

      - name: Install/upgrade chart
        run: >
          export KUBECONFIG=$GITHUB_WORKSPACE/.kubeconfig && 
          make ci-deploy latest_sha=$(echo $GITHUB_SHA | head -c7) 
          db_connection_string=${{ secrets.DB_URL }} rails_master_key=${{secrets.RAILS_MASTER_KEY}}
